import type { Metadata } from 'next';
import { AuthProvider } from '@/core/auth/AuthContext';
import AuthGuard from '@/core/auth/AuthGuard';
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <AuthGuard>{children}</AuthGuard>
        </AuthProvider>
    );
}
